#!/usr/bin/env python3
"""Build China events Excel for Sep 15 – Dec 15, 2026 (major cities/regions)."""

from datetime import datetime
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

OUT = Path(__file__).resolve().parents[1] / "output" / "china_events_2026_09_to_12.xlsx"
COLLECTED_AT = "2026-09-15"
WINDOW = "2026-09-15 ~ 2026-12-15"

# Column order matches user request (+ helper metadata columns)
HEADERS = [
    "title",
    "owner",
    "start_time",
    "end_time",
    "people_limits",
    "address",
    "links",
    "poster",
    "price",
    "category",
    "province",
    "city",
    "how_to_pay",
    "source_type",  # ticketed_listing / government / chamber_expat / social_mention / media_roundup
    "audience",  # chinese / foreigner / mixed
    "confidence",  # high / medium / low
    "notes",
]

# Each row: dict keyed by HEADERS
EVENTS = [
    # —— Beijing ——
    {
        "title": "毛不易2026「只在今夜」演唱会-北京站",
        "owner": "毛不易巡演主办方（购票通/大麦渠道转载）",
        "start_time": "2026-09-26 19:00",
        "end_time": "2026-09-26 22:00",
        "people_limits": "大型体育场；以票务库存为准（未公布精确容量）",
        "address": "北京工人体育场，北京市东城区工人体育场北路",
        "links": "http://qianpiaotong.cn/mobile/Product/64990.shtml",
        "poster": "",
        "price": "待平台公布（售票中）",
        "category": "演唱会",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "支付宝/微信/现金/预存款（购票通）；大麦等同渠道以平台为准",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "公开售票信息；具体开演时刻以现场/票面为准",
    },
    {
        "title": "徐良“时间折叠”演唱会-北京站（连演）",
        "owner": "徐良巡演主办方",
        "start_time": "2026-10-01",
        "end_time": "2026-10-07",
        "people_limits": "场馆容量；连演七场，以每场票房为准",
        "address": "华熙生物·润百颜ECM中心，北京市海淀区复兴路69号",
        "links": "http://goupiaotong.cn/Product/65155.shtml",
        "poster": "",
        "price": "待平台公布",
        "category": "演唱会",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "大麦/猫眼/第三方票务平台支付（支付宝/微信/银行卡）",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "10/1-10/7连演；票价以开售页为准",
    },
    {
        "title": "「整晚哈音乐」庾澄庆2026演唱会-北京站",
        "owner": "庾澄庆巡演主办方 / 大麦",
        "start_time": "2026-10-24 19:00",
        "end_time": "2026-10-24 22:00",
        "people_limits": "场馆容量；以票务库存为准",
        "address": "华熙生物·润百颜ECM中心，北京市海淀区复兴路69号",
        "links": "https://huodong.com/event/detail/eyuce",
        "poster": "",
        "price": "大麦售票（价位待核）",
        "category": "演唱会",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "大麦网（支付宝/微信/银行卡）",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "2026搀扶·马健涛巡回演唱会-北京站",
        "owner": "北京国际流行音乐周 / 马健涛巡演",
        "start_time": "2026-11-29 15:30",
        "end_time": "2026-11-29 18:00",
        "people_limits": "剧场席位有限；以售票为准",
        "address": "北京展览馆剧场，北京市西城区西直门外大街135号",
        "links": "http://www.goupiaotong.cn/Product/64588.shtml",
        "poster": "",
        "price": "VIP699/599/399/299/199/99元",
        "category": "演唱会",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "票务平台在线支付（支付宝/微信等）",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "下午场",
    },
    {
        "title": "地坛书市·博集天卷展位（秋季书市）",
        "owner": "地坛书市组委会 / 博集天卷",
        "start_time": "2026-09-17",
        "end_time": "2026-09-27",
        "people_limits": "公园开放式人流；无固定名额",
        "address": "地坛公园名品精品精出版专区86-90号展位，北京市东城区",
        "links": "https://www.163.com/dy/article/L6QAAM7M0521CK8N.html",
        "poster": "",
        "price": "入园/逛展免费；图书文创现场标价（文创八折起等优惠）",
        "category": "市集/书市",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "现场现金/移动支付购书",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "偏中小型文化市集；适合本地逛展",
    },
    {
        "title": "昌平辛庄艺术村周末生活市集（常态）",
        "owner": "辛庄村商户/主理人自发市集",
        "start_time": "2026-09-15",
        "end_time": "2026-12-15",
        "people_limits": "开放式村落市集；无固定上限",
        "address": "北京市昌平区辛庄村及上下苑艺术村一带",
        "links": "https://travelnews.qunar.com/ugc/beijing-changping-art-weekend",
        "poster": "",
        "price": "免费逛集；摊位商品标价",
        "category": "市集/社区活动",
        "province": "北京市",
        "city": "北京",
        "how_to_pay": "摊位现场支付（微信/支付宝为主）",
        "source_type": "social_mention",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "游记/社交内容提及每周末有市集；具体摊位以当天现场为准（非官方票务清单）",
    },
    # —— Shanghai ——
    {
        "title": "2026周传雄「念念不忘·再遇见plus」巡回演唱会-上海站",
        "owner": "周传雄巡演主办方",
        "start_time": "2026-09-05 19:00",
        "end_time": "2026-09-06 22:00",
        "people_limits": "上海体育场容量；以票务为准",
        "address": "上海体育场，上海市徐汇区天钥桥路666号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "380-1180元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦（支付宝/微信/银行卡）",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "9/5-9/6；若已开演则归档为近期场次参考",
    },
    {
        "title": "2026GAI周延「REAL G」巡回演唱会-上海站",
        "owner": "GAI周延巡演主办方",
        "start_time": "2026-09-05 19:00",
        "end_time": "2026-09-05 22:00",
        "people_limits": "虹口足球场容量",
        "address": "上海虹口足球场，上海市虹口区东江湾路444号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "299-1199元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "潘玮柏“MAD LOVE:ULTRA”巡回演唱会-上海站",
        "owner": "潘玮柏巡演主办方",
        "start_time": "2026-09-19 19:00",
        "end_time": "2026-09-19 22:00",
        "people_limits": "虹口足球场容量",
        "address": "上海虹口足球场，上海市虹口区东江湾路444号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "380-980元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦/票星球",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "2026张智霖“在”巡回演唱会-上海站",
        "owner": "张智霖巡演主办方",
        "start_time": "2026-09-19 19:00",
        "end_time": "2026-09-19 22:00",
        "people_limits": "东方体育中心容量",
        "address": "上海东方体育中心，上海市浦东新区泳耀路300号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "480-1280元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦/票星球",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "第三届上海国际光影节（延中绿地主会场·黄浦）",
        "owner": "上海市黄浦区 / 光影节组委会",
        "start_time": "2026-09-17",
        "end_time": "2026-10-16",
        "people_limits": "开放式绿地展演；高峰人流管控以现场为准",
        "address": "延中绿地黄浦段及上海音乐厅周边，上海市黄浦区",
        "links": "https://c.m.163.com/news/a/L6AMB7BN0514IGIT.html",
        "poster": "",
        "price": "户外光影展免费；市集消费另计",
        "category": "城市文化/光影展",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "免费观展；市集摊位现场支付",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "含光影作品、市集、建筑投影秀等；小红书等社交平台大量种草",
    },
    {
        "title": "第二十五届中国上海国际艺术节",
        "owner": "中国上海国际艺术节中心 / 上海市文旅局",
        "start_time": "2026-10-17",
        "end_time": "2026-11-15",
        "people_limits": "近400项/约1100场；各场次票务/免费惠民名额不同",
        "address": "全市多场馆（上海大歌剧院、各大剧院等）",
        "links": "https://whlyj.sh.gov.cn/yshd/20260826/ed3f0712c24e4b78905a8c8d60ae9986.html",
        "poster": "",
        "price": "专业演出售票 + 惠民免费场次并存",
        "category": "艺术节/演出展览",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "各大剧院票务/大麦等；惠民场预约渠道以官方为准",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "含大量国际节目；外国人观众友好",
    },
    {
        "title": "Charlie Puth: Whatever's Clever! World Tour 上海站",
        "owner": "Charlie Puth 巡演 / 中国承办方",
        "start_time": "2026-10-31 19:00",
        "end_time": "2026-11-01 22:00",
        "people_limits": "虹口足球场容量",
        "address": "上海虹口足球场，上海市虹口区东江湾路444号",
        "links": "https://huodong.com/event/detail/eydDt",
        "poster": "",
        "price": "待官方票价页确认",
        "category": "演唱会（国际）",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "大麦/猫眼等主流票务",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "外国艺人中国巡演；受众含外籍乐迷",
    },
    {
        "title": "林志炫ONEtake3.0耳顺.顺耳巡回演唱会-上海站",
        "owner": "林志炫巡演主办方",
        "start_time": "2026-10-31 19:00",
        "end_time": "2026-10-31 22:00",
        "people_limits": "东方体育中心容量",
        "address": "上海东方体育中心，上海市浦东新区泳耀路300号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "432-1280元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "2026EDC雏菊电音嘉年华唤醒之夜",
        "owner": "EDC China / 电音节承办方",
        "start_time": "2026-10-05 14:00",
        "end_time": "2026-10-05 23:59",
        "people_limits": "大型户外电音节；以票种分区容量为准",
        "address": "上海复兴岛岛北公共空间，上海市杨浦区",
        "links": "http://sh.bendibao.com/news/2026914/309200.shtm",
        "poster": "",
        "price": "单日票V区780 / A区580 / B区480元",
        "category": "音乐节/电音节",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/票星球/大麦",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "国际电音品牌中国场",
    },
    {
        "title": "2026上海青浦水岸音乐季（谭盾 / 彩虹合唱团）",
        "owner": "上海青浦水岸音乐季组委会",
        "start_time": "2026-10-06 15:00",
        "end_time": "2026-10-07 17:00",
        "people_limits": "公园演出席位；以票务为准",
        "address": "上达中央公园南园（南门：青安路833号），上海市青浦区",
        "links": "http://sh.bendibao.com/news/2026914/309200.shtm",
        "poster": "",
        "price": "280/180/100元（早鸟优惠期有限）",
        "category": "音乐会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "大麦",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "10/6谭盾武侠三部曲；10/7彩虹室内合唱团",
    },
    {
        "title": "安溥 2026 to ebb 潮水箴言演唱会-上海站",
        "owner": "安溥巡演主办方",
        "start_time": "2026-11-14 19:00",
        "end_time": "2026-11-15 22:00",
        "people_limits": "梅奔文化中心容量",
        "address": "梅赛德斯-奔驰文化中心，上海市浦东新区世博大道1200号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "480-680元",
        "category": "演唱会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "猫眼/大麦/票星球",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "J. Cole - The Fall-Off World Tour 上海站（审批信息）",
        "owner": "J. Cole 巡演中国承办方（待官宣）",
        "start_time": "2026-11-20 19:30",
        "end_time": "2026-11-21 22:00",
        "people_limits": "梅奔文化中心容量",
        "address": "上海梅赛德斯-奔驰文化中心，上海市浦东新区世博大道1200号",
        "links": "https://news.qq.com/rain/a/20260903A05XJZ00",
        "poster": "",
        "price": "待公布",
        "category": "演唱会（国际）",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "待票务开售（预计主流票务平台）",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "文旅审批消息；最终以主办方官宣为准",
    },
    {
        "title": "小红书市集「新秀现场」",
        "owner": "小红书 / 入选原创商家主理人",
        "start_time": "2026-09-12",
        "end_time": "2026-09-16",
        "people_limits": "约100家商家；观众免费预约（名额以预约系统为准）",
        "address": "世博创意秀场，上海市黄浦区世博浦西片区",
        "links": "https://finance.sina.com.cn/jjxw/2026-09-15/doc-inirwmwa7005834.shtml",
        "poster": "",
        "price": "免费预约观展；商品现场标价",
        "category": "市集/品牌快闪",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "免费入场；商品现场移动支付",
        "source_type": "social_mention",
        "audience": "mixed",
        "confidence": "high",
        "notes": "小红书站内商家线下首秀；偏个人/小店主理人事件",
    },
    {
        "title": "虹桥南丰城「秋日嬉书市」",
        "owner": "上海书城 / 虹桥南丰城",
        "start_time": "2026-09-19",
        "end_time": "2026-09-27",
        "people_limits": "约20+摊位；商场人流",
        "address": "虹桥南丰城，上海市长宁区",
        "links": "https://www.shanghai.gov.cn/nw17239/20260904/4ee735e460cd477b8b1c660b31f78df6.html",
        "poster": "",
        "price": "免费逛市；图书文创标价",
        "category": "市集/书市",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "现场支付",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "9/19-20 与 9/25-27 两段",
    },
    {
        "title": "静安寺广场 FUN&IN 茶咖市集",
        "owner": "上海国际茶文化旅游节线下板块 / 商户摊主",
        "start_time": "2026-09-19",
        "end_time": "2026-09-21",
        "people_limits": "30+创意摊位；开放式广场",
        "address": "丰盛里·静安寺广场，上海市静安区",
        "links": "https://news.gujin-shop.com/d/70890.html",
        "poster": "",
        "price": "免费逛集；茶咖手作标价",
        "category": "市集",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "摊位现场支付",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "含秋夜音乐会（9/21）；部分信息来自商圈汇总",
    },
    {
        "title": "长宁「悠享生活季·放一放乐园」生活市集",
        "owner": "长宁区 / 商圈联动",
        "start_time": "2026-10-17",
        "end_time": "2026-10-18",
        "people_limits": "开放式社区活动",
        "address": "C·PARK海粟文化广场，上海市长宁区",
        "links": "https://www.shanghai.gov.cn/nw17239/20260904/4ee735e460cd477b8b1c660b31f78df6.html",
        "poster": "",
        "price": "免费参与为主；消费另计",
        "category": "社区/生活市集",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "现场支付",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "中国国际家具展览会 / 摩登上海设计周（小红书官方账号宣发）",
        "owner": "中国国际家具展览会 / 摩登上海设计周",
        "start_time": "2026-09-07",
        "end_time": "2026-09-11",
        "people_limits": "专业展会观众；需观众证/邀请",
        "address": "上海新国际博览中心一带（以展会官网为准）",
        "links": "https://www.xiaohongshu.com/user/profile/5ea692270000000001008015",
        "poster": "",
        "price": "专业观众通常预登记；现场可能收费",
        "category": "展会/设计周",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "展会观众注册/现场购票",
        "source_type": "social_mention",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "来源：小红书展会官方账号公开笔记摘要；时间窗口边界（9月初）",
    },
    {
        "title": "interpack China 2026（小红书宣发）",
        "owner": "interpack China 主办方",
        "start_time": "2026-11-16",
        "end_time": "2026-11-18",
        "people_limits": "约43000+专业观众规模（主办宣称）",
        "address": "上海新国际博览中心，上海市浦东新区",
        "links": "https://www.xiaohongshu.com/user/profile/636a4f2d000000001f014a84",
        "poster": "",
        "price": "专业观众预登记（常见免费/审核制）",
        "category": "展会",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "观众注册系统",
        "source_type": "social_mention",
        "audience": "mixed",
        "confidence": "high",
        "notes": "包装行业专业展；小红书账号公开宣传",
    },
    {
        "title": "BenCham Shanghai Welcome Back to Business Drinks",
        "owner": "Benelux Chamber of Commerce in Shanghai",
        "start_time": "2026-09-17 19:00",
        "end_time": "2026-09-17 22:00",
        "people_limits": "商会会员活动；名额以报名系统为准",
        "address": "The St. Regis on the Bund - Spago，中山东二路538号21楼，上海市黄浦区",
        "links": "https://benchamshanghai.glueup.cn/event/welcome-back-to-business-drinks-50895/",
        "poster": "",
        "price": "会员288元 / 非会员388元（含轻食与畅饮酒水）",
        "category": "外企商会社交",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "Glue Up 在线报名支付",
        "source_type": "chamber_expat",
        "audience": "foreigner",
        "confidence": "high",
        "notes": "外国人/外企社区活动",
    },
    {
        "title": "AmCham Shanghai Mid-Autumn Festival Mixer",
        "owner": "American Chamber of Commerce in Shanghai",
        "start_time": "2026-09-23 18:00",
        "end_time": "2026-09-23 20:30",
        "people_limits": "以AmCham报名名额为准",
        "address": "Fairmont Peace Hotel Terrace 915，南京东路20号，上海市黄浦区",
        "links": "https://amcham-shanghai.glueup.cn/event/mid-autumn-festival-mixer-51263/",
        "poster": "",
        "price": "以AmCham票种页为准（含招牌饮品）",
        "category": "外企商会社交",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "Glue Up / AmCham 在线支付",
        "source_type": "chamber_expat",
        "audience": "foreigner",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "Shanghai Expat Association September Welcome Chat",
        "owner": "Shanghai Expat Association (SEA)",
        "start_time": "2026-09-30 10:00",
        "end_time": "2026-09-30 12:00",
        "people_limits": "小型座谈；RSVP截止9/28 17:00",
        "address": "The Coffee Tree (Ferguson Lane)，上海市徐汇区武康路一带",
        "links": "https://www.shanghaisea.com/events/september-welcome-chat-7",
        "poster": "",
        "price": "聊天免费；入会400元现金（护照核验）",
        "category": "外籍社区活动",
        "province": "上海市",
        "city": "上海",
        "how_to_pay": "RSVP在线；入会现金",
        "source_type": "chamber_expat",
        "audience": "foreigner",
        "confidence": "high",
        "notes": "面向持非内地护照人士为主",
    },
    # —— Shenzhen ——
    {
        "title": "G.E.M.邓紫棋 I AM GLORIA 巡回演唱会-深圳站",
        "owner": "邓紫棋巡演主办方",
        "start_time": "2026-09-11 19:00",
        "end_time": "2026-10-02 22:00",
        "people_limits": "大运中心体育场容量；多场连演",
        "address": "深圳大运中心体育场，深圳市龙岗区",
        "links": "https://www.xinruipiao.com/yanchanghui/32123.html",
        "poster": "",
        "price": "以大麦/猫眼开售页为准",
        "category": "演唱会",
        "province": "广东省",
        "city": "深圳",
        "how_to_pay": "大麦/猫眼",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "场次含9/11-13、19-20、25-27及10/1-2",
    },
    {
        "title": "郭富城《ICONIC》世界巡回演唱会2026-深圳站",
        "owner": "郭富城巡演主办方",
        "start_time": "2026-09-26 19:00",
        "end_time": "2026-09-26 22:00",
        "people_limits": "场馆容量；以票务为准",
        "address": "深圳大运中心（场馆以官宣为准），深圳市龙岗区",
        "links": "https://www.xinruipiao.com/yanchanghui/32123.html",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "广东省",
        "city": "深圳",
        "how_to_pay": "主流票务平台",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "排期汇总站点；请以大麦官宣为准",
    },
    {
        "title": "2026深圳“一带一路”国际音乐季",
        "owner": "深圳“一带一路”国际音乐季组委会",
        "start_time": "2026-09-11",
        "end_time": "2026-11-01",
        "people_limits": "25台34场；各场次容量不同",
        "address": "龙岗国际艺术中心等全市多场馆，深圳市",
        "links": "https://sz.ifeng.com/c/8wJKjjevGPY",
        "poster": "",
        "price": "各场次单独售票/部分惠民",
        "category": "国际音乐季",
        "province": "广东省",
        "city": "深圳",
        "how_to_pay": "剧院票务/大麦等",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "含多国艺术家；外国人友好",
    },
    {
        "title": "第34届中国（深圳）国际礼品及家居用品展览会",
        "owner": "励展华博展览（深圳）有限公司",
        "start_time": "2026-10-20",
        "end_time": "2026-10-23",
        "people_limits": "主办预计约30万人次观众",
        "address": "深圳国际会展中心（新馆），深圳市宝安区福海街道展城路1号",
        "links": "https://www.dahaoexpo.com/index.php/expo/44792",
        "poster": "",
        "price": "专业观众预登记为主",
        "category": "展会",
        "province": "广东省",
        "city": "深圳",
        "how_to_pay": "观众注册系统",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "InterChamber Networking Drinks 跨商会商务社交酒会（深圳）",
        "owner": "中国德国商会华南及西南地区（联合多家国际商会）",
        "start_time": "2026-09-16 18:30",
        "end_time": "2026-09-16 21:30",
        "people_limits": "约150人量级",
        "address": "Residence G Shenzhen · Summer Palace，深圳市南山区东滨路4078号",
        "links": "https://www.bagevent.com/event/9248289",
        "poster": "",
        "price": "250元起",
        "category": "外企商会社交",
        "province": "广东省",
        "city": "深圳",
        "how_to_pay": "白鸽/Glue Up 在线支付",
        "source_type": "chamber_expat",
        "audience": "foreigner",
        "confidence": "high",
        "notes": "多国商会联办",
    },
    # —— Chengdu ——
    {
        "title": "薛之谦“万兽之王”巡回演唱会-成都站",
        "owner": "薛之谦巡演主办方",
        "start_time": "2026-10-01 19:00",
        "end_time": "2026-10-11 22:00",
        "people_limits": "东安湖主体育场容量；多场",
        "address": "成都东安湖体育公园主体育场，成都市",
        "links": "http://cd.bendibao.com/xiuxian/2026910/213629.shtm",
        "poster": "",
        "price": "317-1717元",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "猫眼/大麦",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "场次：10/1-3、6-7、10-11",
    },
    {
        "title": "“万物安生时”李健巡回演唱会-成都站",
        "owner": "李健巡演主办方",
        "start_time": "2026-10-03 19:00",
        "end_time": "2026-10-05 22:00",
        "people_limits": "体育馆容量",
        "address": "五粮液文化体育中心综合体育馆，成都市",
        "links": "http://cd.bendibao.com/xiuxian/2026910/213629.shtm",
        "poster": "",
        "price": "380-1880元",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "大麦等",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "许嵩2026「安泊猜想」巡演-成都站",
        "owner": "许嵩巡演主办方",
        "start_time": "2026-10-23 19:00",
        "end_time": "2026-10-25 22:00",
        "people_limits": "场馆容量",
        "address": "成都市（具体场馆以官宣为准）",
        "links": "https://c.m.163.com/news/a/L6F4K7750514FD4Q.html",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "10/23、10/25",
    },
    {
        "title": "威神V [BORN THIS Way] 演唱会-成都站",
        "owner": "AEG Asia / 威神V",
        "start_time": "2026-10-07 19:00",
        "end_time": "2026-10-07 22:00",
        "people_limits": "金融城演艺中心容量",
        "address": "成都金融城演艺中心，成都市",
        "links": "https://c.m.163.com/news/a/L6F4K7750514FD4Q.html",
        "poster": "",
        "price": "大麦售票",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "大麦",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "跨国偶像团体；外籍粉丝亦常见",
    },
    {
        "title": "周华健2026“少年的奇幻之旅 3.0”巡回演唱会-成都站",
        "owner": "周华健巡演主办方",
        "start_time": "2026-11-28 19:00",
        "end_time": "2026-11-28 22:00",
        "people_limits": "体育馆容量",
        "address": "成都五粮液文化体育中心综合体育馆",
        "links": "https://c.m.163.com/news/a/L6F4K7750514FD4Q.html",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "单依纯成都演唱会",
        "owner": "单依纯巡演主办方",
        "start_time": "2026-09-12 19:00",
        "end_time": "2026-09-13 22:00",
        "people_limits": "体育馆容量",
        "address": "成都五粮液文化体育中心综合体育馆",
        "links": "https://c.m.163.com/news/a/L6F4K7750514FD4Q.html",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "王源成都演唱会",
        "owner": "王源巡演主办方",
        "start_time": "2026-09-19 19:00",
        "end_time": "2026-09-20 22:00",
        "people_limits": "东安湖主体育场容量",
        "address": "成都东安湖体育公园主体育场",
        "links": "https://c.m.163.com/news/a/L6F4K7750514FD4Q.html",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "四川省",
        "city": "成都",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    # —— Chongqing ——
    {
        "title": "王力宏「最好的地方II」世界巡回演唱会-重庆站",
        "owner": "王力宏巡演主办方",
        "start_time": "2026-09-12 19:00",
        "end_time": "2026-09-13 22:00",
        "people_limits": "奥体中心体育场容量",
        "address": "重庆奥体中心体育场，重庆市九龙坡区奥林匹克体育中心",
        "links": "https://huodong.com/event/detail/eyuH3",
        "poster": "",
        "price": "以票务平台为准",
        "category": "演唱会",
        "province": "重庆市",
        "city": "重庆",
        "how_to_pay": "大麦/猫眼等",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "谢霆锋 Evolution Nic Live 进化演唱会-重庆站",
        "owner": "谢霆锋巡演主办方",
        "start_time": "2026-09-26 19:00",
        "end_time": "2026-09-27 22:00",
        "people_limits": "奥体中心体育场容量",
        "address": "重庆奥体中心体育场，重庆市九龙坡区",
        "links": "https://www.huanghepiao.com/event/41566/",
        "poster": "",
        "price": "380元起",
        "category": "演唱会",
        "province": "重庆市",
        "city": "重庆",
        "how_to_pay": "票务平台支付",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "中秋档",
    },
    {
        "title": "刘若英 [飞行日] 2026巡回演唱会-重庆站",
        "owner": "刘若英巡演 / 必应创造等制作团队",
        "start_time": "2026-10-17 19:00",
        "end_time": "2026-10-17 22:00",
        "people_limits": "华熙ECM中心容量",
        "address": "华熙生物·润百颜ECM中心，重庆市巴南区平江东路5号",
        "links": "http://cq.bendibao.com/xiuxian/202684/166408.shtm",
        "poster": "",
        "price": "399/699/899/1099/1299元",
        "category": "演唱会",
        "province": "重庆市",
        "city": "重庆",
        "how_to_pay": "大麦",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "秦昊Jeff“光阴的模样”巡演-重庆站",
        "owner": "秦昊Jeff巡演主办方",
        "start_time": "2026-11-21 19:00",
        "end_time": "2026-11-21 21:00",
        "people_limits": "剧院席位；儿童需购全票",
        "address": "重庆市劳动人民文化宫大剧院",
        "links": "https://huodong.com/event/detail/eyaPj",
        "poster": "",
        "price": "剧院票价以开售页为准",
        "category": "演唱会/剧场演出",
        "province": "重庆市",
        "city": "重庆",
        "how_to_pay": "实名电子票平台支付",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "约100分钟无中场",
    },
    # —— Changsha ——
    {
        "title": "威神V [BORN THIS Way] 演唱会-长沙站",
        "owner": "AEG Asia / 威神V",
        "start_time": "2026-10-11 18:30",
        "end_time": "2026-10-11 21:00",
        "people_limits": "贺龙体育馆容量",
        "address": "湖南贺龙体育馆，长沙市天心区芙蓉中路二段188号",
        "links": "https://www.piaoniu.com/activity/785349",
        "poster": "",
        "price": "499/699/899/1099/1699元",
        "category": "演唱会",
        "province": "湖南省",
        "city": "长沙",
        "how_to_pay": "大麦",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "周深2026《深深的》巡回演唱会-长沙站",
        "owner": "周深巡演主办方",
        "start_time": "2026-10-17 19:00",
        "end_time": "2026-10-18 22:30",
        "people_limits": "贺龙体育场容量；每账户每场限购4张",
        "address": "长沙贺龙体育场，长沙市天心区",
        "links": "http://cs.bendibao.com/xiuxian/202693/137829.shtm",
        "poster": "",
        "price": "大麦开售价为准",
        "category": "演唱会",
        "province": "湖南省",
        "city": "长沙",
        "how_to_pay": "大麦",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "high",
        "notes": "连演两场，约3.5小时",
    },
    {
        "title": "杨丞琳《房间里的大象》世界巡回演唱会-长沙站",
        "owner": "杨丞琳巡演主办方",
        "start_time": "2026-11-14 19:30",
        "end_time": "2026-11-14 22:00",
        "people_limits": "芒果馆容量",
        "address": "湖南国际会展中心·芒果馆，长沙市开福区三一大道471号",
        "links": "https://m.juzimima.com/event/40405/",
        "poster": "",
        "price": "380元起",
        "category": "演唱会",
        "province": "湖南省",
        "city": "长沙",
        "how_to_pay": "票务平台支付",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    # —— Xinjiang ——
    {
        "title": "中国郎·遇见美好乌鲁木齐巅峰演唱会",
        "owner": "中国郎系列演唱会主办方",
        "start_time": "2026-09-13 21:00",
        "end_time": "2026-09-13 23:30",
        "people_limits": "奥体中心体育场容量",
        "address": "乌鲁木齐奥体中心体育场，乌鲁木齐市米东区会展大道4000号",
        "links": "https://www.piaoniu.com/activity/781974",
        "poster": "",
        "price": "以票务平台为准",
        "category": "演唱会",
        "province": "新疆维吾尔自治区",
        "city": "乌鲁木齐",
        "how_to_pay": "票牛/大麦等",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "阵容含张韶涵、张信哲等",
    },
    {
        "title": "2026昌吉州美食文化旅游节",
        "owner": "昌吉州人民政府 / 节会组委会",
        "start_time": "2026-09-25",
        "end_time": "2026-09-29",
        "people_limits": "开放式节会；主分会场多点",
        "address": "新疆农业博览园主会场；昌吉小吃街、庭州生态绿谷等分会场",
        "links": "https://www.cj.gov.cn/p1/xwfbh/20260910/594970.html",
        "poster": "",
        "price": "节会开放；餐饮/优品展消费另计；有免费品鉴区",
        "category": "美食文化旅游节",
        "province": "新疆维吾尔自治区",
        "city": "昌吉",
        "how_to_pay": "现场消费支付；部分免费",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "含民俗演出、群众才艺、交响音乐会、优品展",
    },
    {
        "title": "Ella陈嘉桦「It’s Me 艾拉主意」巡回演唱会-乌鲁木齐站",
        "owner": "Ella陈嘉桦巡演主办方",
        "start_time": "2026-10-24 21:00",
        "end_time": "2026-10-24 23:30",
        "people_limits": "综合体育馆容量；实名检票",
        "address": "乌鲁木齐奥体中心综合体育馆，乌鲁木齐市米东区会展大道4000号",
        "links": "https://www.huanghepiao.com/article/1788314026161874.html",
        "poster": "",
        "price": "280/480/680/880/980元",
        "category": "演唱会",
        "province": "新疆维吾尔自治区",
        "city": "乌鲁木齐",
        "how_to_pay": "票务平台支付",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "约120分钟",
    },
    # —— Xizang ——
    {
        "title": "第六届中国西藏旅游文化国际博览会（产品展销期）",
        "owner": "西藏自治区人民政府 / 藏博会组委会",
        "start_time": "2026-09-02",
        "end_time": "2026-09-10",
        "people_limits": "392家企业参展；观众开放",
        "address": "西藏会展中心，拉萨市",
        "links": "https://wlt.xizang.gov.cn/xwzx_69/tzgg/202609/t20260901_556185.html",
        "poster": "",
        "price": "展销开放；商品现场标价",
        "category": "博览会/展销",
        "province": "西藏自治区",
        "city": "拉萨",
        "how_to_pay": "现场消费",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "截至采集日(9/15)展销已结束；因窗口内公开信息稀缺仍收录作西藏近期大型事件参考。开幕式等因灾情从简取消。",
    },
    {
        "title": "拉萨后续大型演出/市集（公开信息稀缺占位）",
        "owner": "待补充",
        "start_time": "",
        "end_time": "",
        "people_limits": "",
        "address": "拉萨市（待补充）",
        "links": "",
        "poster": "",
        "price": "",
        "category": "待补充",
        "province": "西藏自治区",
        "city": "拉萨",
        "how_to_pay": "",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "low",
        "notes": "下一季度公开可核验的演唱会/市集清单较少；建议后续重点盯当地文旅局、秀动、大麦拉萨页与小红书同城",
    },
    # —— Guizhou ——
    {
        "title": "汪苏泷巡回演唱会-贵阳站",
        "owner": "汪苏泷巡演主办方",
        "start_time": "2026-09-19 19:00",
        "end_time": "2026-09-20 22:00",
        "people_limits": "奥体中心体育场容量",
        "address": "贵阳奥林匹克体育中心体育场，贵阳市观山湖区",
        "links": "https://travelnews.qunar.com/qa_strategy/guiyang-2026-concert-schedule-accommodation-guide",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "排期来自旅游攻略汇总，建议与大麦核对",
    },
    {
        "title": "Beyond乐队叶世荣「你中有我」巡回演唱会-贵阳站",
        "owner": "叶世荣巡演主办方",
        "start_time": "2026-09-26 19:00",
        "end_time": "2026-09-26 22:00",
        "people_limits": "体育馆容量",
        "address": "贵阳奥体中心二期主体育馆，贵阳市观山湖区云潭南路与石林东路交叉口附近",
        "links": "https://www.huanghepiao.com/article/1788741053161959.html",
        "poster": "",
        "price": "380/480/580/680/780/880元",
        "category": "演唱会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "票务平台支付",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "约3小时",
    },
    {
        "title": "陈楚生巡回演唱会-贵阳站",
        "owner": "陈楚生巡演主办方",
        "start_time": "2026-10-02 19:00",
        "end_time": "2026-10-02 22:00",
        "people_limits": "奥体中心体育场容量",
        "address": "贵阳奥林匹克体育中心体育场",
        "links": "https://travelnews.qunar.com/qa_strategy/guiyang-2026-concert-schedule-accommodation-guide",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "",
    },
    {
        "title": "Groove Coverage 出道25周年巡演-贵阳站",
        "owner": "X-LIVE / Groove Coverage",
        "start_time": "2026-10-15 20:00",
        "end_time": "2026-10-15 21:30",
        "people_limits": "Livehouse/艺术空间容量（相对小型）",
        "address": "市集×煎蛋艺术空间，贵阳市南明区多彩贵州城1958文化创意园区3号楼",
        "links": "https://www.showstart.com/event/299810",
        "poster": "",
        "price": "秀动网售票价为准",
        "category": "Livehouse/国际乐队",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "秀动网（微信/支付宝）",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "德国舞曲乐队；偏小场地国际演出",
    },
    {
        "title": "薛之谦巡回演唱会-贵阳站",
        "owner": "薛之谦巡演主办方",
        "start_time": "2026-10-16",
        "end_time": "2026-10-25",
        "people_limits": "奥体中心体育场容量；多场",
        "address": "贵阳奥林匹克体育中心体育场",
        "links": "https://travelnews.qunar.com/qa_strategy/guiyang-2026-concert-schedule-accommodation-guide",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "多场连演；具体日场以官宣为准",
    },
    {
        "title": "第十六届贵阳汽车文化节暨新能源·智能汽车展",
        "owner": "贵阳车展主办方",
        "start_time": "2026-10-22",
        "end_time": "2026-10-25",
        "people_limits": "约8万人次观众（主办估算）",
        "address": "贵阳国际会议展览中心，贵阳市观山湖区长岭北路1号",
        "links": "https://www.izhans.com/gy/2026060918492.html",
        "poster": "",
        "price": "门票咨询主办；常见为低价/免费领票模式",
        "category": "展会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "现场/预登记",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "贵阳美博会 Guiyang Beauty Expo 2026",
        "owner": "贵州华夏至美展览有限公司",
        "start_time": "2026-11-14",
        "end_time": "2026-11-16",
        "people_limits": "约25000观众 / 370参展企业",
        "address": "贵阳国际会议展览中心，贵阳市观山湖区长岭北路1号",
        "links": "https://www.jufair.com/information/248792.html",
        "poster": "",
        "price": "早鸟票/展期票/限时免费票等",
        "category": "展会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "展会购票/预约系统",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "王力宏巡回演唱会-贵阳站",
        "owner": "王力宏巡演主办方",
        "start_time": "2026-11-20 19:00",
        "end_time": "2026-11-22 22:00",
        "people_limits": "奥体中心体育场容量",
        "address": "贵阳奥林匹克体育中心体育场",
        "links": "https://travelnews.qunar.com/qa_strategy/guiyang-2026-concert-schedule-accommodation-guide",
        "poster": "",
        "price": "待核",
        "category": "演唱会",
        "province": "贵州省",
        "city": "贵阳",
        "how_to_pay": "主流票务",
        "source_type": "media_roundup",
        "audience": "chinese",
        "confidence": "medium",
        "notes": "",
    },
    # —— Hong Kong ——
    {
        "title": "MAMAMOO 2026 WORLD TOUR [4WARD] IN HONG KONG",
        "owner": "Soul N Joy / MAMAMOO",
        "start_time": "2026-10-04 18:00",
        "end_time": "2026-10-04 21:00",
        "people_limits": "启德体艺馆竞技场容量",
        "address": "启德体艺馆（竞技场），香港启德体育园",
        "links": "https://www.mrmiles.hk/mamamoo-concert/",
        "poster": "",
        "price": "HK$999 / 1399 / 1699 / VIP 2099",
        "category": "演唱会（K-pop）",
        "province": "香港特别行政区",
        "city": "香港",
        "how_to_pay": "快达票/大麦/Trip.com/携程（信用卡/支付宝等视平台）",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "BIGBANG 2026-2027 WORLD TOUR <XX : COSMOS> IN HONG KONG",
        "owner": "TME live / ELF ASIA",
        "start_time": "2026-11-13 19:00",
        "end_time": "2026-11-15 22:00",
        "people_limits": "约50,000人/场（启德主场馆）",
        "address": "香港启德体育园主场馆",
        "links": "https://www.prnewswire.com/apac/zh/news-releases/bigbang-2026-2027-world-tour--xx--cosmos--in-hong-kong--302872280.html",
        "poster": "",
        "price": "以公开发售票价为准",
        "category": "演唱会（K-pop）",
        "province": "香港特别行政区",
        "city": "香港",
        "how_to_pay": "Trip.com/Klook/TME等官方渠道",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "11/13-15三场",
    },
    {
        "title": "香港贸发局香港国际美酒展",
        "owner": "香港贸易发展局",
        "start_time": "2026-11-05",
        "end_time": "2026-11-07",
        "people_limits": "专业/公众分区；以票务为准",
        "address": "香港会议展览中心",
        "links": "https://partnernet.hktb.com/china/sc/destination/events_festivals/index.html",
        "poster": "",
        "price": "公众日门票以HKTDC为准",
        "category": "展会",
        "province": "香港特别行政区",
        "city": "香港",
        "how_to_pay": "HKTDC票务/信用卡",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "ReThink HK 2026",
        "owner": "ReThink HK 主办方",
        "start_time": "2026-09-10",
        "end_time": "2026-09-11",
        "people_limits": "会议观众名额",
        "address": "香港（以官网场馆为准）",
        "links": "https://partnernet.hktb.com/china/sc/destination/events_festivals/index.html",
        "poster": "",
        "price": "会议票种以官网为准",
        "category": "会议/可持续发展",
        "province": "香港特别行政区",
        "city": "香港",
        "how_to_pay": "官网报名支付",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "窗口边界日期",
    },
    {
        "title": "SEASONS 时尚首饰及配饰秋季展",
        "owner": "相关展会主办 / 香港贸发局体系活动（以官网为准）",
        "start_time": "2026-09-17",
        "end_time": "2026-09-21",
        "people_limits": "专业买家为主",
        "address": "香港会议展览中心一带",
        "links": "https://partnernet.hktb.com/china/sc/destination/events_festivals/index.html",
        "poster": "",
        "price": "专业观众注册",
        "category": "展会",
        "province": "香港特别行政区",
        "city": "香港",
        "how_to_pay": "展会注册系统",
        "source_type": "government",
        "audience": "mixed",
        "confidence": "medium",
        "notes": "来源：香港旅发局节日盛事列表",
    },
    # —— Macau ——
    {
        "title": "BABYMONSTER WORLD TOUR [춤 (CHOOM)] IN MACAO",
        "owner": "YG Entertainment / 金光票务",
        "start_time": "2026-09-11 20:00",
        "end_time": "2026-09-12 21:00",
        "people_limits": "威尼斯人综艺馆容量；3岁以下不可入场；未满13岁不宜",
        "address": "澳门威尼斯人综艺馆",
        "links": "https://www.cotaiticketing.com/shows/babymonster2026.html",
        "poster": "",
        "price": "MOP/HKD 799/999/1399/1699/VIP2299",
        "category": "演唱会（K-pop）",
        "province": "澳门特别行政区",
        "city": "澳门",
        "how_to_pay": "金光票务 Cotai Ticketing（信用卡等）",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "9/11 20:00；9/12 18:00",
    },
    {
        "title": "刘若英 [飞行日] 2026巡回演唱会—澳门站",
        "owner": "刘若英巡演 / Cityline",
        "start_time": "2026-10-03 19:00",
        "end_time": "2026-10-03 22:00",
        "people_limits": "银河综艺馆容量",
        "address": "澳门银河综艺馆",
        "links": "https://shows.cityline.com.hk/sc/2026/renefinalcall2026macau.html",
        "poster": "",
        "price": "Cityline票价页为准",
        "category": "演唱会",
        "province": "澳门特别行政区",
        "city": "澳门",
        "how_to_pay": "Cityline（信用卡等）",
        "source_type": "ticketed_listing",
        "audience": "chinese",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "2026 Sneaker Con Macau",
        "owner": "Sneaker Con / 澳娱综合",
        "start_time": "2026-10-10",
        "end_time": "2026-10-11",
        "people_limits": "预计逾5000名潮流观众",
        "address": "上葡京综艺馆，澳门上葡京综合度假村",
        "links": "http://macaucee.com.mo/content.asp?id=120711",
        "poster": "",
        "price": "早鸟两日票约MOP399起；标准票约MOP699（含联名T恤套装信息以官网为准）",
        "category": "潮流展会/音乐会",
        "province": "澳门特别行政区",
        "city": "澳门",
        "how_to_pay": "Trip.com/携程",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "含潮流音乐会嘉宾",
    },
    # —— Taiwan ——
    {
        "title": "IVE WORLD TOUR「SHOW WHAT I AM」台北站",
        "owner": "IVE 巡演台湾承办方",
        "start_time": "2026-09-11",
        "end_time": "2026-09-13",
        "people_limits": "台北小巨蛋容量；三场",
        "address": "台北小巨蛋，台北市松山区南京东路四段2号",
        "links": "https://tw.trip.com/blog/kstars-in-tw2026/",
        "poster": "",
        "price": "以拓元/宽宏等售票为准",
        "category": "演唱会（K-pop）",
        "province": "台湾",
        "city": "台北",
        "how_to_pay": "拓元/KKTIX/宽宏（信用卡/超商）",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "BIGBANG WORLD TOUR《XX : COSMOS》台北站",
        "owner": "BIGBANG 巡演台湾承办方",
        "start_time": "2026-10-10",
        "end_time": "2026-10-11",
        "people_limits": "台北大巨蛋容量",
        "address": "台北大巨蛋，台北市信义区",
        "links": "https://tw.trip.com/blog/kstars-in-tw2026/",
        "poster": "",
        "price": "NT$2,980～9,430",
        "category": "演唱会（K-pop）",
        "province": "台湾",
        "city": "台北",
        "how_to_pay": "官方售票系统",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "MUSIC EXPO LIVE 2026 in TAIPEI",
        "owner": "MUSIC EXPO LIVE / 宽宏售票",
        "start_time": "2026-10-24 18:00",
        "end_time": "2026-10-25 20:00",
        "people_limits": "台北小巨蛋容量",
        "address": "台北小巨蛋",
        "links": "https://www.arena.taipei/News_Content.aspx?n=2E1489AFE4B1BEA1&s=E4E6C8C6312BFA4E&sms=F9A95D3F5A5C2C68",
        "poster": "",
        "price": "宽宏售票（价位以开卖页为准）",
        "category": "音乐节",
        "province": "台湾",
        "city": "台北",
        "how_to_pay": "宽宏售票",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "日本大型音乐节海外首站；主持人樱井翔",
    },
    {
        "title": "Fujii Kaze Prema World Tour - Kaohsiung",
        "owner": "KKLIVE Taiwan / Fujii Kaze",
        "start_time": "2026-10-31 19:00",
        "end_time": "2026-10-31 22:00",
        "people_limits": "高雄国家体育场全座席",
        "address": "高雄国家体育场，高雄市左营区世运大道100号",
        "links": "https://kklivetw.kktix.cc/events/34473ba4",
        "poster": "",
        "price": "NT$1800/2800/3800/4800/5800",
        "category": "演唱会（国际）",
        "province": "台湾",
        "city": "高雄",
        "how_to_pay": "KKTIX",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "BTS WORLD TOUR ARIRANG 2026 高雄站",
        "owner": "BTS 巡演 / 拓元",
        "start_time": "2026-11-19",
        "end_time": "2026-11-22",
        "people_limits": "高雄巨蛋容量；三场",
        "address": "高雄巨蛋（K-ARENA），高雄市左营区博爱二路757号",
        "links": "https://tw.trip.com/blog/kstars-in-tw2026/",
        "poster": "",
        "price": "拓元售票",
        "category": "演唱会（K-pop）",
        "province": "台湾",
        "city": "高雄",
        "how_to_pay": "拓元",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "11/19、21、22",
    },
    {
        "title": "BABYMONSTER WORLD TOUR CHOOM 2026 台北站",
        "owner": "BABYMONSTER 巡演台湾承办方",
        "start_time": "2026-11-21",
        "end_time": "2026-11-22",
        "people_limits": "台北小巨蛋容量",
        "address": "台北小巨蛋",
        "links": "https://tw.trip.com/blog/kstars-in-tw2026/",
        "poster": "",
        "price": "待公布/售票平台",
        "category": "演唱会（K-pop）",
        "province": "台湾",
        "city": "台北",
        "how_to_pay": "官方售票",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "JOJI SOLARIS 高雄巨蛋",
        "owner": "JOJI 巡演承办方",
        "start_time": "2026-11-27 20:00",
        "end_time": "2026-11-27 22:30",
        "people_limits": "高雄巨蛋容量",
        "address": "高雄巨蛋，高雄市左营区博爱二路757号",
        "links": "https://www.kaoarena.com.tw/Home/CalendarDetail?id=270",
        "poster": "",
        "price": "NT$2900起至VIP Package NT$12380",
        "category": "演唱会（国际）",
        "province": "台湾",
        "city": "高雄",
        "how_to_pay": "官方售票系统",
        "source_type": "ticketed_listing",
        "audience": "mixed",
        "confidence": "high",
        "notes": "",
    },
    {
        "title": "Stray Kids 《RUN IT》WORLD TOUR 台北站",
        "owner": "Stray Kids 巡演 / 远大",
        "start_time": "2026-12-12",
        "end_time": "2026-12-12",
        "people_limits": "台北大巨蛋容量",
        "address": "台北大巨蛋",
        "links": "https://tw.trip.com/blog/kstars-in-tw2026/",
        "poster": "",
        "price": "远大售票",
        "category": "演唱会（K-pop）",
        "province": "台湾",
        "city": "台北",
        "how_to_pay": "远大售票",
        "source_type": "media_roundup",
        "audience": "mixed",
        "confidence": "high",
        "notes": "接近三月窗口末端",
    },
]


COVERAGE = [
    ["region", "status", "notes"],
    ["北京", "good", "演唱会+书市+社区市集；外企活动公开页较少"],
    ["上海", "strong", "演唱会/艺术节/市集/商会/小红书市集较全"],
    ["深圳", "good", "演唱会+音乐季+展会+跨商会酒会"],
    ["成都", "good", "演唱会密集；小市集公开核验较少"],
    ["重庆", "good", "演唱会为主"],
    ["长沙", "fair", "大型演唱会有；小店活动公开源少"],
    ["新疆", "fair", "乌鲁木齐演唱会+昌吉节会"],
    ["西藏", "weak", "藏博会刚结束；后续公开清单稀缺"],
    ["贵州", "good", "贵阳演唱会+车展+美博会+Livehouse"],
    ["香港", "good", "演唱会+贸发局展会列表"],
    ["澳门", "good", "演唱会+Sneaker Con"],
    ["台湾", "strong", "台北/高雄演唱会与音乐节"],
]


SOURCES = [
    ["source", "type", "url_example"],
    ["大麦/猫眼/票星球/购票通/票牛/秀动", "ticketed_listing", "damai.cn / showstart.com"],
    ["本地宝 / 文旅局 / 政府新闻发布", "government_media", "bendibao / whlyj.sh.gov.cn"],
    ["国际商会 Glue Up / Bagevent / SEA", "chamber_expat", "glueup.cn"],
    ["小红书公开账号/媒体转述", "social_mention", "xiaohongshu.com"],
    ["香港旅发局节日盛事 / HKTDC", "government", "partnernet.hktb.com"],
]


def style_header(ws):
    fill = PatternFill("solid", fgColor="1F4E79")
    font = Font(color="FFFFFF", bold=True)
    thin = Border(
        left=Side(style="thin", color="D9D9D9"),
        right=Side(style="thin", color="D9D9D9"),
        top=Side(style="thin", color="D9D9D9"),
        bottom=Side(style="thin", color="D9D9D9"),
    )
    for col, h in enumerate(HEADERS, 1):
        cell = ws.cell(1, col, h)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(wrap_text=True, vertical="center")
        cell.border = thin
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}1"


def autosize(ws, widths=None):
    defaults = {
        "title": 42,
        "owner": 28,
        "start_time": 18,
        "end_time": 18,
        "people_limits": 28,
        "address": 40,
        "links": 36,
        "poster": 18,
        "price": 28,
        "category": 18,
        "province": 16,
        "city": 12,
        "how_to_pay": 28,
        "source_type": 16,
        "audience": 12,
        "confidence": 12,
        "notes": 40,
    }
    for i, h in enumerate(HEADERS, 1):
        ws.column_dimensions[get_column_letter(i)].width = (widths or defaults).get(h, 18)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()

    # Events sheet
    ws = wb.active
    ws.title = "events"
    style_header(ws)
    for r, ev in enumerate(EVENTS, 2):
        for c, h in enumerate(HEADERS, 1):
            val = ev.get(h, "")
            cell = ws.cell(r, c, val)
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    autosize(ws)
    ws.row_dimensions[1].height = 22

    # Coverage
    ws2 = wb.create_sheet("coverage")
    for r, row in enumerate(COVERAGE, 1):
        for c, val in enumerate(row, 1):
            cell = ws2.cell(r, c, val)
            if r == 1:
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="1F4E79")
        ws2.column_dimensions[get_column_letter(r and 1)].width = 14
    for i, w in enumerate([14, 12, 50], 1):
        ws2.column_dimensions[get_column_letter(i)].width = w

    # Sources
    ws3 = wb.create_sheet("sources")
    for r, row in enumerate(SOURCES, 1):
        for c, val in enumerate(row, 1):
            cell = ws3.cell(r, c, val)
            if r == 1:
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="1F4E79")
    for i, w in enumerate([40, 18, 40], 1):
        ws3.column_dimensions[get_column_letter(i)].width = w

    # Meta
    ws4 = wb.create_sheet("meta")
    meta_rows = [
        ["field", "value"],
        ["collected_at", COLLECTED_AT],
        ["time_window", WINDOW],
        ["regions", "北京,上海,深圳,成都,重庆,长沙,新疆,西藏,贵州,香港,澳门,台湾"],
        ["event_count", str(len(EVENTS))],
        ["method", "Public web listings + government/media roundups + indexed social mentions (not full Douyin/XHS scrape)"],
        ["poster_note", "Poster URLs rarely exposed in crawlable HTML; column left blank unless a stable public image URL is available. Prefer link column for verification."],
        ["disclaimer", "Not exhaustive. Prices/dates/venues change; always verify on official ticketing pages before purchase. Social mentions are noisy and may lack exact capacity/payment fields."],
    ]
    for r, row in enumerate(meta_rows, 1):
        for c, val in enumerate(row, 1):
            cell = ws4.cell(r, c, val)
            if r == 1:
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="1F4E79")
    ws4.column_dimensions["A"].width = 16
    ws4.column_dimensions["B"].width = 100

    wb.save(OUT)
    print(f"Wrote {OUT} with {len(EVENTS)} events")


if __name__ == "__main__":
    main()
